-- Talvia initial PostgreSQL schema. Review before running in Neon SQL Editor.
begin;
create extension if not exists pgcrypto;

create table users (id uuid primary key default gen_random_uuid(), email text not null, first_name text not null default '', last_name text not null default '', avatar_url text, locale varchar(16) not null default 'fr', timezone text not null default 'Africa/Brazzaville', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index users_email_lower_unique on users(lower(email));
create table workspaces (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'), owner_user_id uuid not null references users(id) on delete restrict, default_locale varchar(16) not null default 'fr', default_timezone text not null default 'Africa/Brazzaville', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table workspace_members (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, user_id uuid not null references users(id) on delete cascade, role varchar(16) not null default 'member' check (role in ('owner','admin','member')), status varchar(16) not null default 'active' check (status in ('active','invited','suspended')), joined_at timestamptz not null default now(), unique(workspace_id,user_id));
create index workspace_members_user_idx on workspace_members(user_id,workspace_id);

create table companies (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, name text not null, domain text, website_url text, industry text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index companies_workspace_domain_unique on companies(workspace_id,lower(domain)) where domain is not null;
create table contacts (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, company_id uuid references companies(id) on delete set null, first_name text not null default '', last_name text not null default '', display_name text not null, job_title text, status varchar(24) not null default 'new' check (status in ('new','lead','prospect','follow_up','qualified','client','inactive','other')), notes_summary text, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index contacts_workspace_active_name_idx on contacts(workspace_id,archived_at,display_name);
create index contacts_workspace_company_idx on contacts(workspace_id,company_id);
create table contact_identities (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, contact_id uuid not null references contacts(id) on delete cascade, channel_type varchar(24) not null check (channel_type in ('linkedin','whatsapp','email','instagram','other')), provider varchar(64), identifier text not null, identifier_normalized text not null check (length(trim(identifier_normalized))>0), profile_url text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,channel_type,identifier_normalized));
create index contact_identities_contact_idx on contact_identities(contact_id,channel_type);

create table connections (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, provider varchar(64) not null, channel_type varchar(24) not null check (channel_type in ('linkedin','whatsapp','email','instagram','other')), external_account_id text not null, display_name text not null, status varchar(24) not null default 'disconnected' check (status in ('disconnected','connecting','syncing','connected','error')), connected_at timestamptz, last_synced_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,provider,external_account_id));
create index connections_workspace_status_idx on connections(workspace_id,status);
create table conversations (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, connection_id uuid not null references connections(id) on delete restrict, contact_id uuid references contacts(id) on delete set null, channel_type varchar(24) not null, external_thread_id text not null, subject text, status varchar(24) not null default 'open' check (status in ('open','closed','archived')), last_message_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(connection_id,external_thread_id));
create index conversations_workspace_last_message_idx on conversations(workspace_id,last_message_at desc);
create table conversation_participants (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references conversations(id) on delete cascade, contact_id uuid references contacts(id) on delete set null, external_participant_id text not null, role varchar(24) not null default 'recipient' check (role in ('sender','recipient','cc','bcc','member')), metadata jsonb not null default '{}'::jsonb, unique(conversation_id,external_participant_id));
create table messages (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, conversation_id uuid not null references conversations(id) on delete cascade, provider_message_id text, direction varchar(16) not null check (direction in ('inbound','outbound')), sender_contact_id uuid references contacts(id) on delete set null, body text not null default '', message_type varchar(24) not null default 'text', status varchar(24) not null default 'pending' check (status in ('pending','sent','delivered','failed','read')), sent_at timestamptz, received_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create unique index messages_provider_id_unique on messages(conversation_id,provider_message_id) where provider_message_id is not null;
create index messages_timeline_idx on messages(conversation_id,coalesce(sent_at,received_at,created_at),id);
create table message_attachments (id uuid primary key default gen_random_uuid(), message_id uuid not null references messages(id) on delete cascade, type varchar(24) not null, file_url text not null, file_name text, mime_type text, size_bytes bigint check (size_bytes is null or size_bytes>=0), created_at timestamptz not null default now());

create table campaigns (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, name text not null, objective varchar(32) not null check (objective in ('prospecting','follow_up','reactivation')), channel_type varchar(24), status varchar(24) not null default 'draft' check (status in ('draft','active','paused','completed','archived')), created_by_user_id uuid references users(id) on delete set null, settings jsonb not null default '{}'::jsonb, started_at timestamptz, paused_at timestamptz, completed_at timestamptz, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index campaigns_workspace_status_idx on campaigns(workspace_id,status,updated_at desc);
create table campaign_steps (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references campaigns(id) on delete cascade, position integer not null check(position>=0), step_type varchar(24) not null check(step_type in ('message','wait','follow_up','end')), channel_type varchar(24), delay_value integer not null default 0 check(delay_value>=0), delay_unit varchar(16) not null default 'minutes' check(delay_unit in ('minutes','hours','days')), message_template text, settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(campaign_id,position));
create table campaign_participants (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references campaigns(id) on delete cascade, contact_id uuid not null references contacts(id) on delete restrict, status varchar(24) not null default 'waiting' check(status in ('waiting','active','replied','completed','stopped')), current_step_id uuid references campaign_steps(id) on delete set null, started_at timestamptz, last_action_at timestamptz, replied_at timestamptz, stopped_at timestamptz, stop_reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(campaign_id,contact_id));
create index campaign_participants_status_idx on campaign_participants(campaign_id,status);

create table opportunities (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, contact_id uuid not null references contacts(id) on delete restrict, conversation_id uuid references conversations(id) on delete set null, campaign_id uuid references campaigns(id) on delete set null, name text not null, stage varchar(24) not null default 'new' check(stage in ('new','qualified','proposal','negotiation','won','lost')), status varchar(16) not null default 'open' check(status in ('open','won','lost')), value_minor bigint check(value_minor is null or value_minor>=0), currency char(3) not null default 'XAF' check(currency ~ '^[A-Z]{3}$'), next_action text, next_action_at timestamptz, lost_reason varchar(32) check(lost_reason is null or lost_reason in ('price','no_need','not_now','competitor','no_response','other')), closed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check((status='open' and closed_at is null) or status in ('won','lost')));
create index opportunities_pipeline_idx on opportunities(workspace_id,status,stage,updated_at desc);
create index opportunities_next_action_idx on opportunities(workspace_id,next_action_at) where status='open' and next_action_at is not null;
create table contact_notes (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, contact_id uuid not null references contacts(id) on delete cascade, author_user_id uuid references users(id) on delete set null, body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index contact_notes_timeline_idx on contact_notes(contact_id,created_at desc);
create table opportunity_notes (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, opportunity_id uuid not null references opportunities(id) on delete cascade, author_user_id uuid references users(id) on delete set null, body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index opportunity_notes_timeline_idx on opportunity_notes(opportunity_id,created_at desc);

create table activities (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, actor_type varchar(24) not null, actor_id uuid, event_type varchar(64) not null, entity_type varchar(32) not null, entity_id uuid not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index activities_workspace_created_idx on activities(workspace_id,created_at desc);
create index activities_entity_created_idx on activities(workspace_id,entity_type,entity_id,created_at desc);
create table automations (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, name text not null, status varchar(16) not null default 'active' check(status in ('draft','active','paused','archived')), trigger_type varchar(64) not null, trigger_config jsonb not null default '{}'::jsonb, condition_config jsonb not null default '{}'::jsonb, action_type varchar(64) not null, action_config jsonb not null default '{}'::jsonb, reply_mode varchar(16) check(reply_mode is null or reply_mode in ('draft','auto')), delay_seconds integer not null default 0 check(delay_seconds>=0), created_by_user_id uuid references users(id) on delete set null, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index automations_workspace_status_idx on automations(workspace_id,status);
create table automation_runs (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, automation_id uuid not null references automations(id) on delete cascade, activity_id uuid references activities(id) on delete set null, status varchar(16) not null check(status in ('success','skipped','failed')), started_at timestamptz not null default now(), completed_at timestamptz, error_message text, result_summary text, created_at timestamptz not null default now());
create index automation_runs_timeline_idx on automation_runs(automation_id,created_at desc);

create table plans (id uuid primary key default gen_random_uuid(), code varchar(64) not null unique, name text not null, description text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table plan_limits (id uuid primary key default gen_random_uuid(), plan_id uuid not null references plans(id) on delete cascade, limit_key varchar(64) not null, limit_value bigint not null check(limit_value>=0), created_at timestamptz not null default now(), unique(plan_id,limit_key));
create table subscriptions (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, plan_id uuid references plans(id) on delete set null, provider varchar(64), provider_customer_id text, provider_subscription_id text, status varchar(24) not null default 'trialing' check(status in ('trialing','active','past_due','canceled','expired')), billing_cycle varchar(16) check(billing_cycle is null or billing_cycle in ('monthly','yearly')), current_period_start timestamptz, current_period_end timestamptz, cancel_at_period_end boolean not null default false, trial_ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index subscriptions_provider_unique on subscriptions(provider,provider_subscription_id) where provider_subscription_id is not null;
create table credit_wallets (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, balance_minor bigint not null default 0 check(balance_minor>=0), updated_at timestamptz not null default now(), unique(workspace_id));
create table credit_transactions (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, wallet_id uuid not null references credit_wallets(id) on delete restrict, amount_minor bigint not null check(amount_minor<>0), reason varchar(64) not null, reference_type varchar(32), reference_id uuid, created_at timestamptz not null default now());
create index credit_transactions_wallet_idx on credit_transactions(wallet_id,created_at desc);
create table webhook_events (id uuid primary key default gen_random_uuid(), workspace_id uuid references workspaces(id) on delete set null, provider varchar(64) not null, external_event_id text not null, event_type varchar(128) not null, payload jsonb not null, status varchar(16) not null default 'received' check(status in ('received','processed','failed','ignored')), processed_at timestamptz, created_at timestamptz not null default now(), unique(provider,external_event_id));
create index webhook_events_status_idx on webhook_events(status,created_at);
create table ai_usage (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, user_id uuid references users(id) on delete set null, feature varchar(64) not null, provider varchar(64), model varchar(128), input_tokens integer not null default 0 check(input_tokens>=0), output_tokens integer not null default 0 check(output_tokens>=0), cost_minor bigint check(cost_minor is null or cost_minor>=0), currency char(3) not null default 'USD' check(currency ~ '^[A-Z]{3}$'), status varchar(16) not null default 'success' check(status in ('success','failed','canceled')), created_at timestamptz not null default now());
create index ai_usage_workspace_idx on ai_usage(workspace_id,created_at desc);

commit;
