import { database } from "./database";
import { createDraft } from "./inbox";
import type { ActivityRecord } from "./activities";
import type { WorkspaceContext } from "./workspace-context";

export type AutomationStatus = "active" | "inactive" | "archived";
export type AutomationInput = { name: string; description?: string; status?: AutomationStatus; triggerType: string; triggerConfig?: Record<string, unknown>; conditionConfig?: Record<string, unknown>; actionType: string; actionConfig?: Record<string, unknown>; replyMode?: "draft" | "auto"; delaySeconds?: number };
export type AutomationRecord = AutomationInput & { id: string; workspaceId: string; createdAt: string; updatedAt: string; lastRunAt?: string; lastRunStatus?: string };
type Row = { id:string; workspace_id:string; name:string; description:string|null; status:AutomationStatus; trigger_type:string; trigger_config:Record<string,unknown>; condition_config:Record<string,unknown>; action_type:string; action_config:Record<string,unknown>; reply_mode:"draft"|"auto"|null; delay_seconds:number; created_at:string; updated_at:string; last_run_at:string|null; last_run_status:string|null };

const select = `select a.*, latest.created_at last_run_at, latest.status last_run_status from automations a left join lateral(select created_at,status from automation_runs where automation_id=a.id order by created_at desc limit 1) latest on true`;
const map = (row: Row): AutomationRecord => ({ id:row.id, workspaceId:row.workspace_id, name:row.name, description:row.description ?? undefined, status:row.status, triggerType:row.trigger_type, triggerConfig:row.trigger_config ?? {}, conditionConfig:row.condition_config ?? {}, actionType:row.action_type, actionConfig:row.action_config ?? {}, replyMode:row.reply_mode ?? undefined, delaySeconds:row.delay_seconds, createdAt:row.created_at, updatedAt:row.updated_at, lastRunAt:row.last_run_at ?? undefined, lastRunStatus:row.last_run_status ?? undefined });
function validate(input: AutomationInput) { if (!input.name.trim()) throw new Error("Le nom est requis."); if (!input.triggerType || !input.actionType) throw new Error("Le déclencheur et l’action sont requis."); if ((input.delaySeconds ?? 0) < 0) throw new Error("Le délai doit être positif."); }

export async function listAutomations(context: WorkspaceContext, status?: AutomationStatus) { const rows = await database.query<Row>(`${select} where a.workspace_id=$1 and a.archived_at is null ${status ? "and a.status=$2" : ""} order by a.created_at desc`, status ? [context.workspaceId,status] : [context.workspaceId]); return rows.rows.map(map); }
export async function getAutomation(context: WorkspaceContext, id: string) { const rows = await database.query<Row>(`${select} where a.workspace_id=$1 and a.id=$2 and a.archived_at is null`, [context.workspaceId,id]); return rows.rows[0] ? map(rows.rows[0]) : null; }
export async function createAutomation(context: WorkspaceContext, input: AutomationInput) { validate(input); const rows = await database.query<Row>(`insert into automations(workspace_id,name,description,status,trigger_type,trigger_config,condition_config,action_type,action_config,reply_mode,delay_seconds,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning id,workspace_id,name,description,status,trigger_type,trigger_config,condition_config,action_type,action_config,reply_mode,delay_seconds,created_at,updated_at,null::timestamptz last_run_at,null::text last_run_status`, [context.workspaceId,input.name.trim(),input.description?.trim()||null,input.status??"inactive",input.triggerType,input.triggerConfig??{},input.conditionConfig??{},input.actionType,input.actionConfig??{},input.replyMode??null,input.delaySeconds??0,context.userId]); return map(rows.rows[0]!); }
export async function updateAutomation(context: WorkspaceContext, id: string, input: Partial<AutomationInput>) { const current = await getAutomation(context,id); if (!current) return null; const next: AutomationInput = {...current,...input,name:input.name?.trim()??current.name}; validate(next); const result = await database.query(`update automations set name=$1,description=$2,status=$3,trigger_type=$4,trigger_config=$5,condition_config=$6,action_type=$7,action_config=$8,reply_mode=$9,delay_seconds=$10,updated_at=now() where workspace_id=$11 and id=$12 and archived_at is null returning id`, [next.name,next.description??null,next.status,next.triggerType,next.triggerConfig??{},next.conditionConfig??{},next.actionType,next.actionConfig??{},next.replyMode??null,next.delaySeconds??0,context.workspaceId,id]); return result.rowCount ? getAutomation(context,id) : null; }
export async function archiveAutomation(context: WorkspaceContext, id: string) { return Boolean((await database.query(`update automations set status='archived',archived_at=now(),updated_at=now() where workspace_id=$1 and id=$2 and archived_at is null returning id`,[context.workspaceId,id])).rowCount); }
export async function duplicateAutomation(context: WorkspaceContext, id: string) { const source = await getAutomation(context,id); return source ? createAutomation(context,{...source,name:`${source.name} (copie)`,status:"inactive"}) : null; }
export async function listRuns(context: WorkspaceContext,id:string) { if(!await getAutomation(context,id)) return null; return (await database.query(`select id,activity_id,trigger_type,status,started_at,completed_at,error_message,result_summary,created_at from automation_runs where workspace_id=$1 and automation_id=$2 order by created_at desc`,[context.workspaceId,id])).rows; }

const matches = (condition:Record<string,unknown>,activity:ActivityRecord) => Object.entries(condition).every(([key,value]) => activity.metadata?.[key] === value);
async function executeAction(context:WorkspaceContext, automation:AutomationRecord, activity:ActivityRecord, runId:string) {
  const config=automation.actionConfig??{};
  if (automation.actionType === "mark_conversation_to_process") { const id=String(config.conversationId??activity.metadata?.conversationId??activity.entityId); const r=await database.query(`update conversations set to_process_at=now(),updated_at=now() where workspace_id=$1 and id=$2 returning id`,[context.workspaceId,id]); if(!r.rowCount) throw new Error("Conversation introuvable."); return "Conversation marquée à traiter."; }
  if (automation.actionType === "create_reply_draft") { const id=String(config.conversationId??activity.metadata?.conversationId??activity.entityId); const draft=await createDraft(context,id,String(config.body??"Brouillon Talvia à valider."),"automation",runId); if(!draft) throw new Error("Conversation introuvable."); return "Brouillon local créé."; }
  if (automation.actionType === "create_next_action") { const id=String(config.opportunityId??activity.metadata?.opportunityId??activity.entityId); const r=await database.query(`update opportunities set next_action=$1,next_action_at=$2,updated_at=now() where workspace_id=$3 and id=$4 returning id`,[String(config.nextAction??"Relancer la proposition"),config.nextActionAt??new Date(Date.now()+3*86400000).toISOString(),context.workspaceId,id]); if(!r.rowCount) throw new Error("Opportunité introuvable."); return "Prochaine action créée."; }
  if (automation.actionType === "stop_campaign_participant") { const campaignId=String(config.campaignId??activity.metadata?.campaignId??""); const contactId=String(config.contactId??activity.metadata?.contactId??""); const r=await database.query(`update campaign_participants p set status='stopped',stopped_at=now(),stop_reason='automation',updated_at=now() from campaigns c where p.campaign_id=c.id and c.workspace_id=$1 and c.id=$2 and p.contact_id=$3 returning p.id`,[context.workspaceId,campaignId,contactId]); if(!r.rowCount) throw new Error("Participant de campagne introuvable."); return "Participant arrêté."; }
  if (automation.actionType === "update_contact_status") { const id=String(config.contactId??activity.metadata?.contactId??activity.entityId); const r=await database.query(`update contacts set status=$1,updated_at=now() where workspace_id=$2 and id=$3 and archived_at is null returning id`,[String(config.status??"qualified"),context.workspaceId,id]); if(!r.rowCount) throw new Error("Contact introuvable."); return "Statut contact mis à jour."; }
  if (automation.actionType === "add_contact_note") { const id=String(config.contactId??activity.metadata?.contactId??activity.entityId); const r=await database.query(`insert into contact_notes(workspace_id,contact_id,author_user_id,body) select $1,id,$2,$3 from contacts where workspace_id=$1 and id=$4 and archived_at is null returning id`,[context.workspaceId,context.userId,String(config.body??"Note ajoutée par une automatisation."),id]); if(!r.rowCount) throw new Error("Contact introuvable."); return "Note contact ajoutée."; }
  throw new Error("Action V1 non prise en charge.");
}

export async function processActivity(activity: ActivityRecord) {
  if (activity.source === "automation") return;
  const rows = await database.query<Row>(`${select} where a.workspace_id=$1 and a.status='active' and a.archived_at is null and a.trigger_type=$2`,[activity.workspaceId,activity.eventType]);
  const context:WorkspaceContext={workspaceId:activity.workspaceId,userId:activity.actorUserId,authUserId:"automation",role:"owner"};
  for (const row of rows.rows) {
    const automation=map(row);
    const inserted=await database.query<{id:string}>(`insert into automation_runs(workspace_id,automation_id,activity_id,trigger_type,status) values($1,$2,$3,$4,'skipped') on conflict(automation_id,activity_id) where activity_id is not null do nothing returning id`,[activity.workspaceId,automation.id,activity.id,activity.eventType]);
    if(!inserted.rowCount) continue;
    const runId=inserted.rows[0]!.id;
    if(!matches(automation.conditionConfig??{},activity)) { await database.query(`update automation_runs set completed_at=now(),result_summary='Conditions non satisfaites.' where id=$1`,[runId]); continue; }
    try { const summary=await executeAction(context,automation,activity,runId); await database.query(`update automation_runs set status='success',completed_at=now(),result_summary=$2 where id=$1`,[runId,summary]); }
    catch(error) { await database.query(`update automation_runs set status='failed',completed_at=now(),error_message=$2 where id=$1`,[runId,error instanceof Error?error.message:"Action impossible."]); }
  }
}

export async function testAutomation(context:WorkspaceContext,id:string) { const automation=await getAutomation(context,id); if(!automation)return null; const entityId=String(automation.actionConfig?.conversationId??automation.actionConfig?.opportunityId??"00000000-0000-0000-0000-000000000000"); const created=await database.query<{id:string;created_at:string}>(`insert into activities(workspace_id,actor_type,actor_id,event_type,entity_type,entity_id,metadata,source) values($1,'user',$2,$3,'conversation',$4,$5,'test') returning id,created_at`,[context.workspaceId,context.userId,automation.triggerType,entityId,{...automation.triggerConfig,isTest:true}]); await processActivity({id:created.rows[0]!.id,workspaceId:context.workspaceId,actorUserId:context.userId,eventType:automation.triggerType,entityType:"conversation",entityId,metadata:{...automation.triggerConfig,isTest:true},source:"test",createdAt:created.rows[0]!.created_at}); return (await listRuns(context,id))?.[0]??null; }
