import { database } from "./database";
import { createDraft } from "./inbox";
import type { ActivityRecord } from "./activities";
import type { WorkspaceContext } from "./workspace-context";

export type AutomationStatus = "active" | "inactive" | "archived";
export type AutomationInput = { name: string; description?: string; status?: AutomationStatus; triggerType: string; triggerConfig?: Record<string, unknown>; conditionConfig?: Record<string, unknown>; actionType: string; actionConfig?: Record<string, unknown>; replyMode?: "draft" | "auto"; delaySeconds?: number };
export type AutomationRecord = AutomationInput & { id: string; workspaceId: string; createdAt: string; updatedAt: string; lastRunAt?: string; lastRunStatus?: string };
type Row = { id:string;workspace_id:string;name:string;description:string|null;status:AutomationStatus;trigger_type:string;trigger_config:Record<string,unknown>;condition_config:Record<string,unknown>;action_type:string;action_config:Record<string,unknown>;reply_mode:"draft"|"auto"|null;delay_seconds:number;created_at:string;updated_at:string;last_run_at:string|null;last_run_status:string|null };
const select = `select a.*, latest.created_at last_run_at, latest.status last_run_status from automations a left join lateral(select created_at,status from automation_runs where automation_id=a.id order by created_at desc limit 1) latest on true`;
const map=(r:Row):AutomationRecord=>({id:r.id,workspaceId:r.workspace_id,name:r.name,description:r.description??undefined,status:r.status,triggerType:r.trigger_type,triggerConfig:r.trigger_config??{},conditionConfig:r.condition_config??{},actionType:r.action_type,actionConfig:r.action_config??{},replyMode:r.reply_mode??undefined,delaySeconds:r.delay_seconds,createdAt:r.created_at,updatedAt:r.updated_at,lastRunAt:r.last_run_at??undefined,lastRunStatus:r.last_run_status??undefined});
function validate(i:AutomationInput){if(!i.name.trim())throw new Error("Le nom est requis.");if(!i.triggerType||!i.actionType)throw new Error("Le déclencheur et l’action sont requis.");if((i.delaySeconds??0)<0)throw new Error("Le délai doit être positif.");}

export async function listAutomations(c:WorkspaceContext,status?:AutomationStatus){const q=await database.query<Row>(`${select} where a.workspace_id=$1 and a.archived_at is null ${status?"and a.status=$2":""} order by a.created_at desc`,status?[c.workspaceId,status]:[c.workspaceId]);return q.rows.map(map);}
export async function getAutomation(c:WorkspaceContext,id:string){const q=await database.query<Row>(`${select} where a.workspace_id=$1 and a.id=$2 and a.archived_at is null`,[c.workspaceId,id]);return q.rows[0]?map(q.rows[0]):null;}
export async function createAutomation(c:WorkspaceContext,input:AutomationInput){validate(input);const q=await database.query<Row>(`insert into automations(workspace_id,name,description,status,trigger_type,trigger_config,condition_config,action_type,action_config,reply_mode,delay_seconds,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning id,workspace_id,name,description,status,trigger_type,trigger_config,condition_config,action_type,action_config,reply_mode,delay_seconds,created_at,updated_at,null::timestamptz last_run_at,null::text last_run_status`,[c.workspaceId,input.name.trim(),input.description?.trim()||null,input.status??"inactive",input.triggerType,input.triggerConfig??{},input.conditionConfig??{},input.actionType,input.actionConfig??{},input.replyMode??null,input.delaySeconds??0,c.userId]);return map(q.rows[0]!);}
export async function updateAutomation(c:WorkspaceContext,id:string,input:Partial<AutomationInput>){const current=await getAutomation(c,id);if(!current)return null;const next={...current,...input,name:input.name?.trim()??current.name};validate(next);const q=await database.query(`update automations set name=$1,description=$2,status=$3,trigger_type=$4,trigger_config=$5,condition_config=$6,action_type=$7,action_config=$8,reply_mode=$9,delay_seconds=$10,updated_at=now() where workspace_id=$11 and id=$12 and archived_at is null returning id`,[next.name,next.description??null,next.status,next.triggerType,next.triggerConfig??{},next.conditionConfig??{},next.actionType,next.actionConfig??{},next.replyMode??null,next.delaySeconds??0,c.workspaceId,id]);return q.rowCount?getAutomation(c,id):null;}
export async function archiveAutomation(c:WorkspaceContext,id:string){const q=await database.query(`update automations set status='archived',archived_at=now(),updated_at=now() where workspace_id=$1 and id=$2 and archived_at is null returning id`,[c.workspaceId,id]);return Boolean(q.rowCount);}
export async function duplicateAutomation(c:WorkspaceContext,id:string){const source=await getAutomation(c,id);if(!source)return null;return createAutomation(c,{...source,name:`${source.name} (copie)`,status:"inactive"});}
export async function listRuns(c:WorkspaceContext,id:string){if(!await getAutomation(c,id))return null;return (await database.query(`select id,activity_id,trigger_type,status,started_at,completed_at,error_message,result_summary,created_at from automation_runs where workspace_id=$1 and automation_id=$2 order by created_at desc`,[c.workspaceId,id])).rows;}
function matches(condition:Record<string,unknown>, activity:ActivityRecord){return Object.entries(condition).every(([key,value])=>activity.metadata?.[key]===value);}
async function action(c:WorkspaceContext,automation:AutomationRecord,activity:ActivityRecord){const config=automation.actionConfig??{};const target=String(config.conversationId??activity.metadata?.conversationId??activity.entityId);if(automation.actionType==="mark_conversation_to_process"){const q=await database.query(`update conversations set to_process_at=now(),updated_at=now() where workspace_id=$1 and id=$2 returning id`,[c.workspaceId,target]);if(!q.rowCount)throw new Error("Conversation introuvable.");return "Conversation marquée à traiter.";}if(automation.actionType==="create_reply_draft"){const draft=await createDraft(c,target,String(config.body??"Brouillon Talvia à valider."));if(!draft)throw new Error("Conversation introuvable.");return "Brouillon local créé.";}if(automation.actionType==="create_next_action"){const opportunityId=String(config.opportunityId??activity.metadata?.opportunityId??activity.entityId);const q=await database.query(`update opportunities set next_action=$1,next_action_at=$2,updated_at=now() where workspace_id=$3 and id=$4 returning id`,[String(config.nextAction??"Relancer la proposition"),config.nextActionAt??new Date(Date.now()+3*86400000).toISOString(),c.workspaceId,opportunityId]);if(!q.rowCount)throw new Error("Opportunité introuvable.");return "Prochaine action créée.";}if(automation.actionType==="stop_campaign_participant"){const campaignId=String(config.campaignId??activity.metadata?.campaignId??"");const contactId=String(config.contactId??activity.metadata?.contactId??"");const q=await database.query(`update campaign_participants p set status='stopped',stopped_at=now(),stop_reason='automation',updated_at=now() from campaigns c where p.campaign_id=c.id and c.workspace_id=$1 and c.id=$2 and p.contact_id=$3 returning p.id`,[c.workspaceId,campaignId,contactId]);if(!q.rowCount)throw new Error("Participant de campagne introuvable.");return "Participant arrêté.";}if(automation.actionType==="update_contact_status"){const contactId=String(config.contactId??activity.metadata?.contactId??activity.entityId);const q=await database.query(`update contacts set status=$1,updated_at=now() where workspace_id=$2 and id=$3 and archived_at is null returning id`,[String(config.status??"qualified"),c.workspaceId,contactId]);if(!q.rowCount)throw new Error("Contact introuvable.");return "Statut contact mis à jour.";}if(automation.actionType==="add_contact_note"){const contactId=String(config.contactId??activity.metadata?.contactId??activity.entityId);const q=await database.query(`insert into contact_notes(workspace_id,contact_id,author_user_id,body) select $1,id,$2,$3 from contacts where workspace_id=$1 and id=$4 and archived_at is null returning id`,[c.workspaceId,c.userId,String(config.body??"Note ajoutée par une automatisation."),contactId]);if(!q.rowCount)throw new Error("Contact introuvable.");return "Note contact ajoutée.";}throw new Error("Action V1 non prise en charge.");}
export async function processActivity(activity:ActivityRecord){if(activity.source==="automation")return;const rows=await database.query<Row>(`${select} where a.workspace_id=$1 and a.status='active' and a.archived_at is null and a.trigger_type=$2`,[activity.workspaceId,activity.eventType]);const context:WorkspaceContext={workspaceId:activity.workspaceId,userId:"00000000-0000-0000-0000-000000000000",authUserId:"automation",role:"owner"};for(const row of rows.rows){const automation=map(row);const inserted=await database.query<{id:string}>(`insert into automation_runs(workspace_id,automation_id,activity_id,trigger_type,status) values($1,$2,$3,$4,'skipped') on conflict(automation_id,activity_id) where activity_id is not null do nothing returning id`,[activity.workspaceId,automation.id,activity.id,activity.eventType]);if(!inserted.rowCount)continue;const runId=inserted.rows[0]!.id;if(!matches(automation.conditionConfig??{},activity)){await database.query(`update automation_runs set completed_at=now(),result_summary='Conditions non satisfaites.' where id=$1`,[runId]);continue;}try{const summary=await action(context,automation,activity);await database.query(`update automation_runs set status='success',completed_at=now(),result_summary=$2 where id=$1`,[runId,summary]);}catch(error){await database.query(`update automation_runs set status='failed',completed_at=now(),error_message=$2 where id=$1`,[runId,error instanceof Error?error.message:"Action impossible."]);}}}
export async function testAutomation(c:WorkspaceContext,id:string){const automation=await getAutomation(c,id);if(!automation)return null;const entityId=String(automation.actionConfig?.conversationId??automation.actionConfig?.opportunityId??"00000000-0000-0000-0000-000000000000");const a:ActivityRecord={id:(await database.query<{id:string}>(`insert into activities(workspace_id,actor_type,actor_id,event_type,entity_type,entity_id,metadata,source) values($1,'user',$2,$3,'conversation',$4,$5,'test') returning id`,[c.workspaceId,c.userId,automation.triggerType,entityId,{...automation.triggerConfig,isTest:true}])).rows[0]!.id,workspaceId:c.workspaceId,eventType:automation.triggerType,entityType:"conversation",entityId,metadata:{...automation.triggerConfig,isTest:true},source:"test",createdAt:new Date().toISOString()};await processActivity(a);return (await listRuns(c,id))?.[0]??null;}
