import type { PoolClient } from "pg";

import { database } from "./database";
import type { WorkspaceContext } from "./workspace-context";

export type CampaignChannel = "linkedin" | "whatsapp" | "email";
export type CampaignObjective = "prospecting" | "follow_up" | "reactivation";
export type CampaignStatus = "draft" | "active" | "paused" | "completed" | "archived";
export type CampaignStepType = "message" | "wait" | "follow_up" | "end";
export type ParticipantStatus = "waiting" | "active" | "replied" | "completed" | "stopped";

export type CampaignStepInput = { id?: string; position: number; stepType: CampaignStepType; channelType?: CampaignChannel; delayValue?: number; delayUnit?: "minutes" | "hours" | "days"; messageTemplate?: string };
export type CampaignInput = { name: string; objective: CampaignObjective; channelType: CampaignChannel; description?: string; participantIds?: string[]; steps?: CampaignStepInput[]; stopOnReply?: boolean };
export type CampaignRecord = { id: string; name: string; objective: CampaignObjective; channelType: CampaignChannel; status: CampaignStatus; description?: string; stopOnReply: boolean; startedAt?: string; pausedAt?: string; completedAt?: string; archivedAt?: string; createdAt: string; updatedAt: string; participantCount: number; steps: CampaignStepInput[]; participants: CampaignParticipantRecord[] };
export type CampaignParticipantRecord = { id: string; contactId: string; name: string; company?: string; status: ParticipantStatus; currentStepId?: string; startedAt?: string; repliedAt?: string; stoppedAt?: string; stopReason?: string };

type CampaignRow = { id:string; name:string; objective:CampaignObjective; channel_type:CampaignChannel; status:CampaignStatus; settings:{description?:string;stopOnReply?:boolean}; started_at:string|null; paused_at:string|null; completed_at:string|null; archived_at:string|null; created_at:string; updated_at:string; participant_count:string };
type StepRow = { id:string; position:number; step_type:CampaignStepType; channel_type:CampaignChannel|null; delay_value:number; delay_unit:"minutes"|"hours"|"days"; message_template:string|null };
type ParticipantRow = { id:string; contact_id:string; display_name:string; company:string|null; status:ParticipantStatus; current_step_id:string|null; started_at:string|null; replied_at:string|null; stopped_at:string|null; stop_reason:string|null };

function invalid(message:string): never { throw new Error(message); }
function validateInput(input:CampaignInput) { if (!input.name?.trim()) invalid("Le nom de la campagne est requis."); if (!input.objective || !input.channelType) invalid("L’objectif et le canal sont requis."); }
function validateSteps(steps:CampaignStepInput[]) { const positions=new Set<number>(); for(const step of steps){ if(!Number.isInteger(step.position)||step.position<0||positions.has(step.position)) invalid("Les étapes doivent avoir des positions uniques."); positions.add(step.position); if(step.delayValue!==undefined&&(!Number.isInteger(step.delayValue)||step.delayValue<0)) invalid("Le délai doit être positif."); } }
function stepFromRow(row:StepRow):CampaignStepInput { return {id:row.id,position:row.position,stepType:row.step_type,...(row.channel_type?{channelType:row.channel_type}:{}),delayValue:row.delay_value,delayUnit:row.delay_unit,...(row.message_template?{messageTemplate:row.message_template}:{})}; }
function participantFromRow(row:ParticipantRow):CampaignParticipantRecord { return {id:row.id,contactId:row.contact_id,name:row.display_name,...(row.company?{company:row.company}:{}),status:row.status,...(row.current_step_id?{currentStepId:row.current_step_id}:{}),...(row.started_at?{startedAt:row.started_at}:{}),...(row.replied_at?{repliedAt:row.replied_at}:{}),...(row.stopped_at?{stoppedAt:row.stopped_at}:{}),...(row.stop_reason?{stopReason:row.stop_reason}:{})}; }
async function activity(client:PoolClient, context:WorkspaceContext, campaignId:string, event:string) { await client.query(`insert into activities(workspace_id,actor_type,actor_id,event_type,entity_type,entity_id,metadata) values($1,'user',$2,$3,'campaign',$4,jsonb_build_object('source','campaigns_api'))`,[context.workspaceId,context.userId,event,campaignId]); }
async function hasCompatibleIdentity(client:PoolClient, workspaceId:string, contactId:string, channel:CampaignChannel) { const result=await client.query<{id:string}>(`select c.id from contacts c join contact_identities ci on ci.contact_id=c.id and ci.workspace_id=c.workspace_id where c.workspace_id=$1 and c.id=$2 and c.archived_at is null and ci.channel_type=$3 limit 1`,[workspaceId,contactId,channel]); return Boolean(result.rows[0]); }
async function getCampaignRow(client:PoolClient, workspaceId:string, campaignId:string) { const r=await client.query<CampaignRow>(`select c.id,c.name,c.objective,c.channel_type,c.status,c.settings,c.started_at,c.paused_at,c.completed_at,c.archived_at,c.created_at,c.updated_at,count(p.id) participant_count from campaigns c left join campaign_participants p on p.campaign_id=c.id where c.workspace_id=$1 and c.id=$2 group by c.id`,[workspaceId,campaignId]); return r.rows[0]??null; }
async function stepsFor(client:PoolClient,campaignId:string) { const r=await client.query<StepRow>(`select id,position,step_type,channel_type,delay_value,delay_unit,message_template from campaign_steps where campaign_id=$1 order by position asc`,[campaignId]); return r.rows.map(stepFromRow); }
async function participantsFor(client:PoolClient,workspaceId:string,campaignId:string) { const r=await client.query<ParticipantRow>(`select p.id,p.contact_id,c.display_name,co.name company,p.status,p.current_step_id,p.started_at,p.replied_at,p.stopped_at,p.stop_reason from campaign_participants p join contacts c on c.id=p.contact_id and c.workspace_id=$1 left join companies co on co.id=c.company_id and co.workspace_id=c.workspace_id where p.campaign_id=$2 order by c.display_name`,[workspaceId,campaignId]); return r.rows.map(participantFromRow); }
async function record(client:PoolClient,workspaceId:string,row:CampaignRow):Promise<CampaignRecord> { return {id:row.id,name:row.name,objective:row.objective,channelType:row.channel_type,status:row.status,description:row.settings?.description,stopOnReply:row.settings?.stopOnReply??true,startedAt:row.started_at??undefined,pausedAt:row.paused_at??undefined,completedAt:row.completed_at??undefined,archivedAt:row.archived_at??undefined,createdAt:row.created_at,updatedAt:row.updated_at,participantCount:Number(row.participant_count),steps:await stepsFor(client,row.id),participants:await participantsFor(client,workspaceId,row.id)}; }

export async function listCampaigns(context:WorkspaceContext) { const client=await database.connect(); try { const r=await client.query<CampaignRow>(`select c.id,c.name,c.objective,c.channel_type,c.status,c.settings,c.started_at,c.paused_at,c.completed_at,c.archived_at,c.created_at,c.updated_at,count(p.id) participant_count from campaigns c left join campaign_participants p on p.campaign_id=c.id where c.workspace_id=$1 and c.status<>'archived' group by c.id order by c.updated_at desc`,[context.workspaceId]); return Promise.all(r.rows.map(row=>record(client,context.workspaceId,row))); } finally { client.release(); } }
export async function getCampaign(context:WorkspaceContext,campaignId:string) { const client=await database.connect(); try { const row=await getCampaignRow(client,context.workspaceId,campaignId); return row?record(client,context.workspaceId,row):null; } finally { client.release(); } }
export async function createCampaign(context:WorkspaceContext,input:CampaignInput) { validateInput(input); const steps=input.steps??[]; validateSteps(steps); const participantIds=[...new Set(input.participantIds??[])]; const client=await database.connect(); try { await client.query("begin"); for(const contactId of participantIds) if(!await hasCompatibleIdentity(client,context.workspaceId,contactId,input.channelType)) invalid("Un contact est introuvable, archivé ou incompatible avec ce canal."); const created=await client.query<{id:string}>(`insert into campaigns(workspace_id,name,objective,channel_type,status,created_by_user_id,settings) values($1,$2,$3,$4,'draft',$5,$6) returning id`,[context.workspaceId,input.name.trim(),input.objective,input.channelType,context.userId,{description:input.description?.trim()||undefined,stopOnReply:input.stopOnReply??true}]); const id=created.rows[0]!.id; for(const step of steps) await client.query(`insert into campaign_steps(campaign_id,position,step_type,channel_type,delay_value,delay_unit,message_template) values($1,$2,$3,$4,$5,$6,$7)`,[id,step.position,step.stepType,step.channelType??input.channelType,step.delayValue??0,step.delayUnit??"days",step.messageTemplate?.trim()||null]); for(const contactId of participantIds) await client.query(`insert into campaign_participants(campaign_id,contact_id,status) values($1,$2,'waiting')`,[id,contactId]); await activity(client,context,id,"campaign.created"); const row=await getCampaignRow(client,context.workspaceId,id); const value=await record(client,context.workspaceId,row!); await client.query("commit"); return value; } catch(error) { await client.query("rollback"); throw error; } finally { client.release(); } }
export async function updateCampaign(context:WorkspaceContext,id:string,input:Partial<CampaignInput>) { const client=await database.connect(); try { const existing=await getCampaignRow(client,context.workspaceId,id); if(!existing)return null; if(existing.status!=="draft" && (input.participantIds||input.steps)) invalid("La séquence et l’audience ne peuvent plus être modifiées après activation."); const name=input.name?.trim()||existing.name; const objective=input.objective??existing.objective; const channel=input.channelType??existing.channel_type; await client.query(`update campaigns set name=$1,objective=$2,channel_type=$3,settings=$4,updated_at=now() where workspace_id=$5 and id=$6`,[name,objective,channel,{...existing.settings,description:input.description?.trim()||existing.settings?.description,stopOnReply:input.stopOnReply??existing.settings?.stopOnReply??true},context.workspaceId,id]); await activity(client,context,id,"campaign.updated"); return record(client,context.workspaceId,(await getCampaignRow(client,context.workspaceId,id))!); } finally { client.release(); } }
export async function transitionCampaign(context:WorkspaceContext,id:string,action:"activate"|"pause"|"resume"|"complete"|"archive") { const client=await database.connect(); try { const current=await getCampaignRow(client,context.workspaceId,id); if(!current)return null; const target={activate:"active",pause:"paused",resume:"active",complete:"completed",archive:"archived"}[action] as CampaignStatus; await client.query(`update campaigns set status=$1,started_at=case when $2='activate' then coalesce(started_at,now()) else started_at end,paused_at=case when $2='pause' then now() else paused_at end,completed_at=case when $2='complete' then now() else completed_at end,archived_at=case when $2='archive' then now() else archived_at end,updated_at=now() where workspace_id=$3 and id=$4`,[target,action,context.workspaceId,id]); if(action==="activate"||action==="resume") await client.query(`update campaign_participants set status='active',started_at=coalesce(started_at,now()),updated_at=now() where campaign_id=$1 and status='waiting'`,[id]); await activity(client,context,id,`campaign.${action==='activate'?'started':action==='resume'?'resumed':action==='pause'?'paused':action==='complete'?'completed':'archived'}`); return record(client,context.workspaceId,(await getCampaignRow(client,context.workspaceId,id))!); } finally { client.release(); } }
export async function addParticipants(context:WorkspaceContext,campaignId:string,contactIds:string[]) { const client=await database.connect(); try { await client.query("begin"); const campaign=await getCampaignRow(client,context.workspaceId,campaignId); if(!campaign){await client.query("rollback");return null;} for(const contactId of [...new Set(contactIds)]) { if(!await hasCompatibleIdentity(client,context.workspaceId,contactId,campaign.channel_type)) invalid("Un contact est introuvable, archivé ou incompatible avec ce canal."); await client.query(`insert into campaign_participants(campaign_id,contact_id,status) values($1,$2,$3) on conflict(campaign_id,contact_id) do nothing`,[campaignId,contactId,campaign.status==='active'?'active':'waiting']); } await activity(client,context,campaignId,"campaign.contact_added"); const value=await record(client,context.workspaceId,(await getCampaignRow(client,context.workspaceId,campaignId))!); await client.query("commit"); return value; } catch(error){await client.query("rollback");throw error;} finally {client.release();} }
export async function stopParticipant(context:WorkspaceContext,campaignId:string,participantId:string,reason="manual") { const client=await database.connect(); try { if(!await getCampaignRow(client,context.workspaceId,campaignId))return null; const r=await client.query(`update campaign_participants set status='stopped',stopped_at=now(),stop_reason=$1,updated_at=now() where id=$2 and campaign_id=$3 returning id`,[reason,participantId,campaignId]); if(!r.rowCount)return null; await activity(client,context,campaignId,"campaign.contact_stopped"); return record(client,context.workspaceId,(await getCampaignRow(client,context.workspaceId,campaignId))!); } finally {client.release();} }
export async function removeParticipant(context:WorkspaceContext,campaignId:string,participantId:string) { const client=await database.connect(); try { const campaign=await getCampaignRow(client,context.workspaceId,campaignId); if(!campaign)return null; if(campaign.status!=="draft")invalid("Les participants d’une campagne active doivent être arrêtés, pas supprimés."); const r=await client.query(`delete from campaign_participants where id=$1 and campaign_id=$2 returning id`,[participantId,campaignId]); if(!r.rowCount)return null; await activity(client,context,campaignId,"campaign.contact_removed"); return record(client,context.workspaceId,(await getCampaignRow(client,context.workspaceId,campaignId))!); } finally {client.release();} }
export async function saveSteps(context:WorkspaceContext,campaignId:string,steps:CampaignStepInput[]) { validateSteps(steps); const client=await database.connect(); try { await client.query("begin"); const campaign=await getCampaignRow(client,context.workspaceId,campaignId); if(!campaign){await client.query("rollback");return null;} if(campaign.status!=="draft")invalid("La séquence ne peut plus être modifiée après activation."); const referenced=await client.query<{current_step_id:string}>(`select current_step_id from campaign_participants where campaign_id=$1 and current_step_id is not null`,[campaignId]); const keep=new Set(steps.flatMap(step=>step.id?[step.id]:[])); for(const row of referenced.rows)if(!keep.has(row.current_step_id))invalid("Une étape utilisée par un participant ne peut pas être supprimée."); await client.query(`delete from campaign_steps where campaign_id=$1`,[campaignId]); for(const step of steps)await client.query(`insert into campaign_steps(campaign_id,position,step_type,channel_type,delay_value,delay_unit,message_template) values($1,$2,$3,$4,$5,$6,$7)`,[campaignId,step.position,step.stepType,step.channelType??campaign.channel_type,step.delayValue??0,step.delayUnit??"days",step.messageTemplate?.trim()||null]); await activity(client,context,campaignId,"campaign.updated"); const value=await record(client,context.workspaceId,(await getCampaignRow(client,context.workspaceId,campaignId))!); await client.query("commit");return value; }catch(error){await client.query("rollback");throw error;}finally{client.release();} }
