import { database } from "./database";
import { getContact } from "./contacts";
import type { WorkspaceContext } from "./workspace-context";

export type OpportunityInput = { title: string; contactId: string; stage: "new" | "qualified" | "proposal" | "negotiation" | "won" | "lost"; value?: number; currency?: string; nextAction?: string; nextActionAt?: string; nextActionCompletedAt?: string; sourceChannel?: string; conversationId?: string; campaignId?: string; notes?: string };
type Row = { id:string; name:string; contact_id:string; contact_name:string; company:string|null; stage:OpportunityInput["stage"]; status:"open"|"won"|"lost"; value_minor:string|null; final_value_minor:string|null; currency:string; next_action:string|null; next_action_at:string|null; next_action_completed_at:string|null; source_channel:string|null; lost_reason:string|null; closed_at:string|null; created_at:string; updated_at:string };
const select = `select o.id,o.name,o.contact_id,c.display_name contact_name,co.name company,o.stage,o.status,o.value_minor,o.final_value_minor,o.currency,o.next_action,o.next_action_at,o.next_action_completed_at,o.source_channel,o.lost_reason,o.closed_at,o.created_at,o.updated_at from opportunities o join contacts c on c.id=o.contact_id and c.workspace_id=o.workspace_id left join companies co on co.id=c.company_id and co.workspace_id=o.workspace_id`;
const money = (value?: number) => value === undefined || value === null || value === "" ? null : Math.round(value * 100);
function map(row: Row) { return { id:row.id,title:row.name,contactId:row.contact_id,contactName:row.contact_name,organization:row.company ?? undefined,stage:row.stage,status:row.status,value:row.value_minor===null?undefined:Number(row.value_minor)/100,finalValue:row.final_value_minor===null?undefined:Number(row.final_value_minor)/100,currency:row.currency,nextAction:row.next_action ?? undefined,nextActionAt:row.next_action_at ?? undefined,nextActionCompletedAt:row.next_action_completed_at ?? undefined,sourceChannel:row.source_channel ?? undefined,lostReason:row.lost_reason ?? undefined,closedAt:row.closed_at ?? undefined,createdAt:row.created_at,updatedAt:row.updated_at }; }
function check(input: OpportunityInput) { if(!input.title?.trim() || !input.contactId) throw new Error("Renseignez un nom et sélectionnez un contact existant."); }
async function activity(context:WorkspaceContext,id:string,event:string) { await database.query(`insert into activities(workspace_id,actor_type,actor_id,event_type,entity_type,entity_id) values($1,'user',$2,$3,'opportunity',$4)`,[context.workspaceId,context.userId,event,id]); }
export async function listOpportunities(context:WorkspaceContext) { const r=await database.query<Row>(`${select} where o.workspace_id=$1 order by o.updated_at desc`,[context.workspaceId]); return r.rows.map(map); }
export async function getOpportunity(context:WorkspaceContext,id:string) { const r=await database.query<Row>(`${select} where o.workspace_id=$1 and o.id=$2`,[context.workspaceId,id]); return r.rows[0]?map(r.rows[0]):null; }
export async function createOpportunity(context:WorkspaceContext,input:OpportunityInput) { check(input); if(!await getContact(context,input.contactId)) throw new Error("Contact introuvable."); const status=input.stage==="won"?"won":input.stage==="lost"?"lost":"open"; const r=await database.query<{id:string}>(`insert into opportunities(workspace_id,contact_id,name,stage,status,value_minor,currency,next_action,next_action_at,source_channel,closed_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning id`,[context.workspaceId,input.contactId,input.title.trim(),input.stage,status,money(input.value),input.currency??"EUR",input.nextAction?.trim()||null,input.nextActionAt||null,input.sourceChannel||null,status==="open"?null:new Date().toISOString()]); const id=r.rows[0]!.id; if(input.notes?.trim()) await addNote(context,id,input.notes); await activity(context,id,"opportunity.created"); return getOpportunity(context,id); }
export async function updateOpportunity(context:WorkspaceContext,id:string,input:OpportunityInput) { check(input); if(!await getContact(context,input.contactId)) throw new Error("Contact introuvable."); const status=input.stage==="won"?"won":input.stage==="lost"?"lost":"open"; const r=await database.query(`update opportunities set contact_id=$1,name=$2,stage=$3,status=$4,value_minor=$5,currency=$6,next_action=$7,next_action_at=$8,next_action_completed_at=$9,source_channel=$10,closed_at=case when $4::varchar='open' then null else coalesce(closed_at,now()) end,updated_at=now() where workspace_id=$11 and id=$12 returning id`,[input.contactId,input.title.trim(),input.stage,status,money(input.value),input.currency??"EUR",input.nextAction?.trim()||null,input.nextActionAt||null,input.nextActionCompletedAt||null,input.sourceChannel||null,context.workspaceId,id]); if(!r.rowCount)return null; await activity(context,id,input.nextActionCompletedAt?"opportunity.next_action_updated":"opportunity.updated"); return getOpportunity(context,id); }
export async function closeOpportunity(context:WorkspaceContext,id:string,kind:"won"|"lost",finalValue?:number,lostReason?:string) { const r=await database.query(`update opportunities set stage=$1,status=$1,final_value_minor=$2,lost_reason=$3,closed_at=now(),updated_at=now() where workspace_id=$4 and id=$5 returning id`,[kind,kind==="won"?money(finalValue):null,kind==="lost"?(lostReason??"other"):null,context.workspaceId,id]); if(!r.rowCount)return null; await activity(context,id,kind==="won"?"opportunity.won":"opportunity.lost"); return getOpportunity(context,id); }
export async function addNote(context:WorkspaceContext,id:string,body:string) { const exists=await getOpportunity(context,id); if(!exists)return null; const r=await database.query<{id:string,body:string,created_at:string}>(`insert into opportunity_notes(workspace_id,opportunity_id,author_user_id,body) values($1,$2,$3,$4) returning id,body,created_at`,[context.workspaceId,id,context.userId,body.trim()]); await activity(context,id,"opportunity.note_added"); return r.rows[0]; }
export async function listNotes(context:WorkspaceContext,id:string) { const r=await database.query<{id:string,body:string,created_at:string}>(`select n.id,n.body,n.created_at from opportunity_notes n join opportunities o on o.id=n.opportunity_id where n.workspace_id=$1 and n.opportunity_id=$2 and o.workspace_id=$1 order by n.created_at asc`,[context.workspaceId,id]); return r.rows; }
