'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent, useState } from 'react';
import { authClient } from '../lib/auth-client';
import { AuthSwitch } from './ui/auth-switch';

export default function AuthClient({ mode }: { mode: 'login' | 'signup' }) {
  const router = useRouter(); const signup = mode === 'signup';
  const [show, setShow] = useState(false); const [status, setStatus] = useState<'idle'|'loading'|'done'>('idle'); const [error, setError] = useState(''); const [target, setTarget] = useState<'login'|'signup'|null>(null);
  function go(next: 'login'|'signup') { if (next === mode || target) return; const url = next === 'login' ? '/login' : '/signup'; if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return router.push(url); setTarget(next); window.setTimeout(() => router.push(url), 420); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus('loading'); setError(''); const data = new FormData(event.currentTarget); const email = String(data.get('email') ?? ''); const password = String(data.get('password') ?? ''); const name = String(data.get('name') ?? ''); const result = signup ? await authClient.signUp.email({ email, password, name, callbackURL: '/app' }) : await authClient.signIn.email({ email, password }); if (result.error) { setError(result.error.message ?? 'Impossible de vous connecter.'); setStatus('idle'); return; } setStatus('done'); if (!signup) window.setTimeout(() => router.push('/app'), 250); }
  return <main className={`auth-page auth-page--${mode}${target ? ` is-transitioning-to-${target}` : ''}`}><section className="auth-card" data-mode={mode}><section className="auth-card__form"><Link href="/" className="auth-back">← Retour à l’accueil</Link><div className="auth-form-wrap"><span className="form-kicker">{signup ? 'NOUVEL ESPACE' : 'CONNEXION'}</span><AuthSwitch mode={mode} onNavigate={go} /><h1>{signup ? 'Créez votre espace Talvia' : 'Bon retour parmi nous'}</h1><p>{signup ? 'Quelques informations suffisent pour commencer.' : 'Entrez vos informations pour retrouver votre espace.'}</p>{status === 'done' ? <div className="mock-success"><span>✓</span><h2>{signup ? 'Vérifiez votre adresse e-mail.' : 'Connexion validée.'}</h2><p>{signup ? 'Nous venons de vous envoyer un lien de confirmation.' : 'Votre session est prête.'}</p></div> : <form onSubmit={submit}><div className="demo-note"><span>i</span><p><b>Compte Talvia</b><small>Vos identifiants restent chiffrés et vos données sont isolées dans votre espace.</small></p></div>{signup && <label>Nom complet<input name="name" required placeholder="Votre nom" /></label>}<label>Email professionnel<input name="email" type="email" required placeholder="vous@entreprise.com" /></label><label>Mot de passe<div className="password-field"><input name="password" type={show ? 'text' : 'password'} required minLength={8} placeholder="8 caractères minimum" /><button type="button" onClick={() => setShow(!show)}>{show ? 'Masquer' : 'Afficher'}</button></div></label>{!signup && <div className="form-options"><label><input type="checkbox" /> Se souvenir de moi</label><a href="#">Mot de passe oublié ?</a></div>}<button className="button submit" disabled={status === 'loading'}>{status === 'loading' ? 'Préparation…' : signup ? 'Créer mon espace' : 'Se connecter'} <span>→</span></button>{error && <p className="form-error">{error}</p>}<p className="form-switch">{signup ? 'Vous avez déjà un compte ?' : 'Pas encore de compte ?'} <button onClick={() => go(signup ? 'login' : 'signup')} type="button">{signup ? 'Se connecter' : 'Créer un compte'}</button></p></form>}</div></section><aside className="auth-card__panel"><Link href="/" className="brand"><span className="brand-mark"><i/><i/><i/><i/></span>talvia</Link><div className="auth-panel-copy"><span className="eyebrow">●—●—● Votre espace commercial</span><h2>{signup ? 'Déjà parmi nous ?' : 'Nouveau ici ?'}</h2><p>{signup ? 'Retrouvez vos conversations et vos relances dans un même espace.' : 'Créez votre espace Talvia et gardez le fil de chaque opportunité.'}</p><button className="auth-panel-action" type="button" onClick={() => go(signup ? 'login' : 'signup')}>{signup ? 'Se connecter' : 'Créer mon espace'} →</button></div></aside></section></main>;
}
