import Link from 'next/link';

const conversations = [
  ['SM', 'Sarah M.', 'LinkedIn', 'Oui, une démo cette semaine serait parfaite.', '2 min'],
  ['MD', 'Marc D.', 'WhatsApp', 'Merci pour la proposition, je reviens vers vous.', '18 min'],
  ['SK', 'Studio K', 'Instagram', 'Vous accompagnez aussi les petites équipes ?', '1 h'],
];

function Brand() { return <span className="brand"><span className="brand-mark" aria-hidden="true"><i /><i /><i /><i /></span>talvia</span>; }
function Head({ kicker, title, copy }: { kicker: string; title: string; copy: string }) { return <header className="section-head"><span>{kicker}</span><h2>{title}</h2><p>{copy}</p></header>; }

function Flow() { return <div className="flow-stage"><div className="flow-channels"><span><b>in</b><i>LinkedIn</i><small>3 conversations</small></span><span><b>wa</b><i>WhatsApp</i><small>5 messages</small></span><span><b>ig</b><i>Instagram</i><small>2 demandes</small></span><span><b>@</b><i>Email</i><small>1 proposition</small></span></div><div className="flow-lines" aria-hidden="true"><i /><i /><i /><i /><b>●</b></div><div className="flow-center"><Brand /><small>Tout le contexte. Une seule vue.</small></div></div>; }

function FollowUps() { const items=[['SM','Sarah Mensah','A demandé une démonstration aujourd’hui.','Répondre'],['MD','Marc Dupont','Proposition envoyée il y a 5 jours.','Relancer'],['JN','Jean N.','« Recontactez-moi en août. »','Relancer']]; return <div className="follow-card"><header><div><small>À RELANCER AUJOURD’HUI</small><h3>3 conversations à reprendre</h3></div><span>22 août</span></header>{items.map((x,i)=><article key={x[1]}><i>{x[0]}</i><div><h4>{x[1]} <em>{i===0?'Maintenant':i===1?'5 jours':'Aujourd’hui'}</em></h4><p>{x[2]}</p></div><button>{x[3]} →</button></article>)}<footer><span>✦</span><p><b>Talvia garde le fil.</b><br />Les relances importantes remontent au bon moment.</p></footer></div>; }

function Crm() { return <div className="crm-card"><header><i>SM</i><div><h3>Sarah Mensah</h3><p>Head of Growth · Nova Studio</p></div><span>Proposition</span></header><div className="crm-channels"><b>in</b><b>wa</b><small>2 canaux</small></div><dl><div><dt>Besoin identifié</dt><dd>Suivi commercial multicanal</dd></div><div><dt>Dernière interaction</dt><dd>Aujourd’hui, 09:47</dd></div><div><dt>Prochaine action</dt><dd>Planifier une démonstration</dd></div></dl><section><small>✦ RÉSUMÉ TALVIA</small><p>Sarah cherche à centraliser les prospects de Nova Studio entre LinkedIn et WhatsApp. Intérêt confirmé pour une démo cette semaine.</p></section><footer><span>Contact enrichi depuis la conversation</span><b>Mis à jour à l’instant</b></footer></div>; }

function Workflow() { return <div className="workflow">{[['01','✉','Nouveau message','Un prospect vous écrit'],['02','✦','Analyse','Intention et besoin'],['03','◇','Qualification','Contexte structuré'],['04','▦','CRM mis à jour','Sans saisie manuelle'],['05','✓','Validation humaine','Vous décidez d’envoyer']].map((x,i)=><div className={i===4?'human':''} key={x[0]}><span>{x[0]}</span><i>{x[1]}</i><b>{x[2]}</b><small>{x[3]}</small></div>)}</div>; }

export function LandingSections() { return <>
  <section className="problem section" id="fonctionnalites"><div className="section-wrap"><Head kicker="LE PROBLÈME" title="Vos prospects parlent avec vous partout." copy="Votre organisation commerciale ne devrait pas être partout. Les messages se dispersent. Talvia les rassemble avant qu’une opportunité ne se perde." /><Flow /></div></section>
  <section className="feature section"><div className="section-wrap split"><div><Head kicker="CONVERSATIONS" title="Le centre de vos conversations commerciales." copy="Passez d’un prospect à l’autre, pas d’une application à l’autre. Retrouvez le contexte, les relances et les actions utiles avant chaque réponse." /><ul className="benefits"><li><b>Une vue claire</b><span>Filtrez les conversations par canal, statut de lecture ou suivi.</span></li><li><b>Le bon contexte</b><span>Retrouvez l’historique et les informations du contact avant de répondre.</span></li><li><b>Une suite à donner</b><span>Transformez un échange utile en suivi commercial, sans perdre le fil.</span></li></ul></div><div className="mini-inbox"><header><span>Inbox</span><b>8 non lus</b></header><nav>Tout&nbsp;&nbsp;&nbsp; LinkedIn&nbsp;&nbsp;&nbsp; WhatsApp</nav>{conversations.map((c,i)=><article key={c[1]} className={i===0?'selected':''}><i>{c[0]}</i><div><b>{c[1]}</b><small>{c[2]}</small><p>{c[3]}</p></div><time>{c[4]}</time></article>)}</div></div></section>
  <section className="feature intelligence section"><div className="section-wrap split reverse"><div className="intel-visual"><div className="scan-line" /><header><span>✦ Signal commercial à qualifier</span><small>Aperçu produit</small></header><div className="intel-score"><div><small>PRIORITÉ</small><b>À suivre</b></div><em>87%</em></div><dl><div><dt>Intention</dt><dd>Demande de démonstration</dd></div><div><dt>Besoin</dt><dd>Centraliser le suivi commercial</dd></div><div><dt>Contexte</dt><dd>Conversation à qualifier</dd></div><div><dt>Étape suivante</dt><dd>Proposer un créneau</dd></div></dl><footer><small>PROCHAINE ACTION À PRÉPARER</small><b>Proposer deux créneaux cette semaine</b></footer></div><div><Head kicker="CONTEXTE COMMERCIAL" title="Donnez une suite utile à chaque conversation." copy="Talvia relie conversations, contacts et suivi pour vous aider à repérer les signaux commerciaux, qualifier ce qui compte et choisir la prochaine action." /><p className="quote">« Cette conversation mérite un suivi. Voici le contexte pour décider de la suite. »</p></div></div></section>
  <section className="feature section"><div className="section-wrap split"><div><Head kicker="RELANCES INTELLIGENTES" title="Ne perdez plus une opportunité parce que vous avez oublié de relancer." copy="Une vente perdue est parfois simplement une conversation laissée sans suite. Talvia remet la bonne conversation sous vos yeux au bon moment." /><div className="value-note"><b>Chaque relance retrouve son contexte.</b><span>Vous savez pourquoi revenir vers la personne — et quoi lui dire.</span></div></div><FollowUps /></div></section>
  <section className="feature section crm-section"><div className="section-wrap split reverse"><Crm /><div><Head kicker="MÉMOIRE COMMERCIALE" title="Votre suivi commercial se construit au fil des conversations." copy="Conservez l’identité du contact, son entreprise, ses canaux, ses notes et les étapes utiles pour retrouver le bon contexte au bon moment." /><ul className="tick-list"><li>Contacts, entreprise et canaux réunis</li><li>Notes et étapes commerciales faciles à retrouver</li><li>Une opportunité créée après qualification</li></ul></div></div></section>
  <section className="automation section"><div className="section-wrap"><Head kicker="AUTOMATISATIONS" title="Automatisez le travail. Pas la relation." copy="Définissez les règles qui structurent votre suivi, préparent les actions utiles et évitent les oublis. Vous choisissez ce que Talvia prépare et ce que Talvia peut automatiser." /><Workflow /><p className="reassurance"><span>✓</span><b>La relation reste humaine.</b> Vous gardez le contrôle sur les règles et les actions de votre espace.</p></div></section>
  <section className="steps section"><div className="section-wrap"><Head kicker="COMMENT ÇA MARCHE" title="Trois étapes. Rien de plus." copy="Talvia est conçu pour rendre votre suivi commercial plus clair, sans configuration intimidante." /><div className="step-grid">{[['⌁','Préparez votre espace','Configurez vos canaux professionnels au rythme des connexions disponibles.'],['▤','Organisez le contexte','Rassemblez conversations, contacts et notes dans un suivi lisible.'],['✦','Décidez de la suite','Qualifiez les signaux, créez une opportunité et planifiez la prochaine action.']].map((x,i)=><article key={x[1]}><span>{i+1}</span><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
  <section className="pricing section" id="tarifs"><div className="section-wrap pricing-inner"><div><span className="section-kicker">TARIFS</span><h2>Commencez avec votre espace commercial.</h2><p>Talvia prépare ses premières offres. Créez votre espace pour découvrir le produit et être informé des formules à venir.</p></div><div className="pricing-card"><small>ACCÈS DE LANCEMENT</small><h3>Talvia Early</h3><p>Un espace de suivi commercial pensé pour les entrepreneurs, agences et petites équipes.</p><ul><li>✓ Contacts, conversations et opportunités</li><li>✓ Campagnes et suivi structuré</li><li>✓ Automatisations configurables</li></ul><Link className="button" href="/signup">Créer mon espace →</Link><small>Aucun paiement demandé à cette étape.</small></div></div></section>
  <section className="final-cta section"><div><span className="eyebrow">●—●—●&nbsp;&nbsp; Reprenez le fil</span><h2>Vos prochaines opportunités sont peut-être déjà dans vos messages.</h2><p>Transformez vos conversations en contexte, en suivi et en décisions commerciales plus claires.</p><Link className="button" href="/signup">Créer mon espace →</Link></div></section>
  <footer className="footer"><div><Brand /><p>Le poste de travail intelligent de vos conversations commerciales.</p></div><nav><a href="#produit">Produit</a><a href="#fonctionnalites">Fonctionnalités</a><a href="#tarifs">Tarifs</a><Link href="/login">Connexion</Link></nav><small>© 2026 Talvia&nbsp;&nbsp; · &nbsp;&nbsp;<a href="#">Confidentialité</a>&nbsp;&nbsp; · &nbsp;&nbsp;<a href="#">Mentions légales</a></small></footer>
</>; }
