export const INDUSTRY_OPTIONS = [
  "Logiciel / SaaS",
  "E-commerce",
  "Conseil",
  "Marketing & communication",
  "Finance & banque",
  "Assurance",
  "Immobilier",
  "Santé",
  "Éducation & formation",
  "RH & recrutement",
  "Juridique",
  "Industrie & manufacture",
  "Construction & BTP",
  "Transport & logistique",
  "Restauration & hôtellerie",
  "Agriculture & agroalimentaire",
  "Énergie",
  "Médias & divertissement",
  "Associatif / ONG",
  "Administration publique",
  "Artisanat",
  "Beauté & bien-être",
  "Technologie (autre)",
];
